Repository leanix/vsm-gitlab-broker, pull requests merged in 2023-10, with the labels that each got.

#29 CID-2028 Releases version v1.1.0
  build.gradle.kts
Labels: minor

#39 CID-2047 Validates GitLab Groups case-insensitive
  build.gradle.kts
Labels: patch

#42 [CID-2062] Fixing sources dropdown items
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/graphql/GitlabGraphqlProvider.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/WebhookConsumerService.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/domain/GitlabProvider.kt
  src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateServiceTest.kt
  src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/WebhookConsumerServiceImplTest.kt
Labels: bug, patch

#44 Upgrading gradle version v1.2.1
  build.gradle.kts
Labels: patch

#46 CID-2037: Add save integration logs when the validation is successful
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/BaseConnectorService.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/ValidationService.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/adapter/feign/data/IntegrationConfigLogRequest.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/domain/IntegrationConfigLog.kt
  src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/ValidationServiceTest.kt
Labels: enhancement

#45 CID-1976: Update documentation on Limitations on running multiple instances
  docs/gitlab-enterprise-connector.md
Labels: chore

#48 CID-1976: Update log for failing to retrieve assignment
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/AssignmentService.kt
Labels: enhancement

#47 [CID-2060] Gracefully handle unsupported versions
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabClient.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabClientProvider.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabFeignClientProvider.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/data/GitlabVersionResponse.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateService.kt
  src/main/kotlin/net/leanix/vsm/gitlab/broker/shared/exception/VsmException.kt
  src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateServiceTest.kt
Labels: enhancement

#49 CID-2097: Fix Snyk vulnerabilities
  build.gradle.kts
Labels: chore
